apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
        - name: app
          image: your-dockerhub-username/demo:latest
          ports:
            - containerPort: 8080
